name: link_text
description: Easy to use text widget for Flutter apps, which converts inlined urls into working, clickable links. Allows custom styling. 
version: 0.1.4
author: Aleksander Wo≈∫niak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/link_text

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: